### ISSUE TITLE
`dpkg -l` diagnostics

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/dockerimage#2]
Just like we print the ccache stats, I wonder if `dpkg -l` would help us find unneeded dependencies in our docker image.  Might help slim the image down so we can download it faster for CI.

**Comment by tapaswenipathak** [comment]
Pl. reopen if any other ideas, as per discussion on the pull request closing the ticket.

**Comment by tapaswenipathak** [comment]
Pl. reopen if any other thoughts as per discussion on the pull request closed the ticket.
