### ISSUE TITLE
Publish a stable image

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/dockerimage#21]
The current brakge caused by clang trunk has highlighted the downside of having one CI job do testing of two projects (the kernel, and clang). If a kernel patch is committed while clang is broken, we won't see it until clang is fixed.

In addition, others are using this project for other efforts (eg. I'm using it internally on our enterprise Travis instance for some CI).

We could tag a Jenkins build that contains a known good version of clang. This could be a known-good trunk build, or a build from the current stable series.

**Comment by nathanchance** [comment]
Yes, this is a very good point.

I do have it set up to tag our images by date when pushing so it would be easy to pin CI to a known working image.

However, I think it would also be good to get an image with the stable/qualifying branch of Clang rolling then wiring up a few CI jobs with it (I don't think doubling our matrix would be a good idea but we can at least make sure mainline stays good).

I'll try to think about how to properly do that tonight.
