### ISSUE TITLE
upgrade to clang-12

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/dockerimage#52]
via @tstellar , it sounds like clang-11 branch was cut.  We should upgrade the docker image check against clang-11 to clang-12. cc @nathanchance

**Comment by nathanchance** [comment]
Correct, I noticed this earlier. We will need to wait for apt.llvm.org binaries before we cut over here.

**Comment by nickdesaulniers** [comment]
cc @sylvestre

**Comment by sylvestre** [comment]
-11 & -12 haven been uploaded in Debian:
https://twitter.com/DebianNew/status/1283580985922260993
https://twitter.com/DebianNew/status/1283565883051433984

(still in NEW)
I will update apt.llvm.org in the next few days!

**Comment by sylvestre** [comment]
11 is mostly built
12 is on going

**Comment by nickdesaulniers** [comment]
fixed by https://github.com/ClangBuiltLinux/dockerimage/pull/53 / https://github.com/ClangBuiltLinux/continuous-integration/pull/288 .
